on:
  push:
    branches:
      - master
    
name: foobar

jobs:
  render:
    name: "Render Rmd"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: "Install rmarkdown"
        run: Rscript -e 'install.packages("rmarkdown")'
      - name: "Render it"
        run: Rscript -e "rmarkdown::render('foobar.Rmd')"
      - name: release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          draft: false
          prerelease: false
          release_name: "something"
          tag_name: v1