on:
 push:
  branches: master

name: "Try upload artifact"


jobs:
 build:
  name: "Upload artifact"
  runs-on: ubuntu-latest
  container: xmjandrews/verse:20.07.15
  steps:
   - name: "Checkout master"
     uses: actions/checkout@v2
     with:
      ref: 'master'
     #   - uses: r-lib/actions/setup-r@v1
     #   - uses: r-lib/actions/setup-pandoc@v1
     #   - uses: r-lib/actions/setup-tinytex@v1
     #   - name: "Install rmarkdown"
     #run: Rscript -e 'install.packages("rmarkdown")'
   - name: Set outputs
     id: vars
     run: echo "::set-output name=date::$(date +'%y.%m.%d')"
     run: echo "::set-output name=sha::$(git rev-parse --short HEAD)"
   - name: "Render it"
     run: Rscript -e "rmarkdown::render('foobar.Rmd')"
   - name: 'Upload artifact'
     uses: actions/upload-artifact@v2
     with:
      name: the-build-${{ steps.vars.outputs.date }}-${{ steps.vars.outputs.sha }}
      path: |
       foobar.pdf
       foobar.Rmd
