on:
 push:
  branches: master

name: "Try upload artifact"


jobs:
 build:
  name: "Upload artifact"
  runs-on: ubuntu-latest
  container: xmjandrews/verse:20.07.15
  steps:
   - name: "Checkout master"
     uses: actions/checkout@v2
     with:
      ref: 'master'
     #   - uses: r-lib/actions/setup-r@v1
     #   - uses: r-lib/actions/setup-pandoc@v1
     #   - uses: r-lib/actions/setup-tinytex@v1
     #   - name: "Install rmarkdown"
     #run: Rscript -e 'install.packages("rmarkdown")'
   - name: Set date
     id: date
     run: echo '::set-output name=DATE::foobar'
   - name: "Render it"
     run: Rscript -e "rmarkdown::render('foobar.Rmd')"
   - name: 'Upload artifact'
     uses: actions/upload-artifact@v2
     with:
      name: the-build-${{ steps.date.outputs.DATE}}
      path: |
       foobar.pdf
       foobar.Rmd
