on:
 push:
  branches: master

name: "Try upload artifact"


jobs:
 build:
  name: "Upload artifact"
  runs-on: ubuntu-latest
  steps:
   - name: "Checkout master"
     uses: actions/checkout@v2
     with:
      ref: 'master'
   - uses: r-lib/actions/setup-r@v1
   - uses: r-lib/actions/setup-pandoc@v1
   - uses: r-lib/actions/setup-tinytex@v1
   - name: "Install rmarkdown"
     run: Rscript -e 'install.packages("rmarkdown")'
   - name: "Render it"
     run: Rscript -e "rmarkdown::render('foobar.Rmd')"
   - name: 'Upload artifact'
     uses: actions/upload-artifact@v2
     with:
      name: artifact
      path: |
       foobar.pdf
       foobar.Rmd
